language: php
sudo: required

php:
  - '7.1.16'

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

before_script:
  - cd app && composer install && cd ..
  - docker-compose up -d

script:
  - cd var && mkdir logs && sudo chmod 777 -R logs && cd ..
  - cd app && php app.php -a fo1 -b bar
