language: php
sudo: required

php:
  - '7.0'

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

before_script:
  - cd app && composer install
  - docker-compose up -d

script:
  - php app/app.php -a fo1 -b bar
