language: php
sudo: required

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

before_script:
  - docker-compose up -d
  - cd app && composer install

script:
  - php app/app.php -a fo1 -b bar
